name: "publish npm"

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm run build
      - run: npm login --registry=https://registry.npmjs.org --scope=@$npm_scope --always-auth
        - npm config set //registry.npmjs.org/:_authToken=NPM_AUTH_TOKEN
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
